DROP TABLE IF EXISTS entries;
CREATE TABLE entries (
  id SERIAL PRIMARY KEY,
  date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR(80) NOT NULL,
  content TEXT NOT NULL
);
